---
title: "Wider Data Creation"
author: "Mathews Philip Venattu"
date: "12/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(lubridate)
library(knitr)
library(kableExtra)
```

## Making Wider Data


```{r }
data1<-read.csv('../Data/15minutes_interval_boeshockData.csv')
bs_data<-read.csv('../Data/bow_shock_only_Data.csv')
join_data<-readRDS('../Data/joined_data.rds', refhook = NULL)
copy_data1<-data1
copy_bs<-bs_data
head(data1)

```

## Loop For making Wider Data

Here I am trying to save the 15 data points befor BS occurs as a columns.
X_KSM1 is the X_KSM data 15 minutes before bowshock occurs similarly other variables.
```{r }
formattedData<-copy_bs%>%select(-c(X.1,X,DOY.UTC.,SCET.s.,deltaTime.s.,date,hour_cross,minute_cross,year_cross,doy_cross,time));

for(bs in c(1:dim(copy_bs)[1])){
  temp=join_data%>%filter(TimeStamp>=bs_data$minlag[bs]&TimeStamp<=bs_data$minlead[bs])
  for(minData in c(1:dim(temp)[1])){
    if(minData!=16){
      
       formattedData[bs,paste("X_KSM",minData,sep = "")]<-temp[minData,'X_KSM.km.']
       formattedData[bs,paste("Y_KSM",minData,sep = "")]<-temp[minData,'Y_KSM.km.']
       formattedData[bs,paste("Z_KSM",minData,sep = "")]<-temp[minData,'Z_KSM.km.']
       formattedData[bs,paste("BX_KSM",minData,sep = "")]<-temp[minData,'BX_KSM.nT.']
       formattedData[bs,paste("BY_KSM",minData,sep = "")]<-temp[minData,'BY_KSM.nT.']
       formattedData[bs,paste("BZ_KSM",minData,sep = "")]<-temp[minData,'BZ_KSM.nT.']
       formattedData[bs,paste("BTot_KSM",minData,sep = "")]<-temp[minData,'BTotal.nT.']
    }
    
  }
  
} 
```

## Output of Above Loop
```{r}

kable(formattedData[1:5, ], "html") %>% kable_styling("striped") %>% scroll_box(width = "100%")
```

## Saving the Output as a CSV file
```{r}
write.csv(formattedData,"15minData_Wider.csv")

```
